server:
  port: 8090
  servlet:
    context-path: /api
spring:
  liquibase:
    enabled: false
  sql:
    init:
      mode: always
      data-locations: classpath:test-data.sql
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true